<?php 
namespace HydraBooking\Admin\Controller;

  // exit
  if ( ! defined( 'ABSPATH' ) ) { exit; }

  class TransStrings {

     public static function getTransStrings(){
        return array(
            //  Dashboard 
            'Dashboard' =>  __('Dashboard', 'hydra-booking'),
            'Booking Overview' =>  __('Booking Overview', 'hydra-booking'),
            'A complete view of all your bookings at a glance.' =>  __('A complete view of all your bookings at a glance.', 'hydra-booking'), 
            'Today' =>  __('Today', 'hydra-booking'),  
            'Last 7 week' =>  __('Last 7 week', 'hydra-booking'), 
            'Last 30 Days' =>  __('Last 30 Days', 'hydra-booking'), 
            'Last 3 months' =>  __('Last 3 months', 'hydra-booking'), 
            'Apply' =>  __('Apply', 'hydra-booking'), 
            'Total Booking' =>  __('Total Booking', 'hydra-booking'), 
            'VS' =>  __('VS', 'hydra-booking'), 
            'Last' =>  __('Last', 'hydra-booking'), 
            'days' =>  __('days', 'hydra-booking'), 
            'Total Earnings' =>  __('Total Earnings', 'hydra-booking'), 
            'Completed Bookings' =>  __('Completed Bookings', 'hydra-booking'), 
            'Canceled Bookings' =>  __('Canceled Bookings', 'hydra-booking'), 
            'Recent Bookings' =>  __('Recent Bookings', 'hydra-booking'), 
            'Free' =>  __('Free', 'hydra-booking'), 
            'No Upcoming Meetings' =>  __('No Upcoming Meetings', 'hydra-booking'), 
            'Upcoming Meetings' =>  __('Upcoming Meetings', 'hydra-booking'), 
            'No Recent Bookings' =>  __('No Recent Bookings', 'hydra-booking'), 
            'Booking Statistics' =>  __('Booking Statistics', 'hydra-booking'), 
            'Last 7 Days' =>  __('Last 7 Days', 'hydra-booking'), 
            'This month' =>  __('This month', 'hydra-booking'), 
            'This Year' =>  __('This Year', 'hydra-booking'), 

            // Booking
            'Back to Booking' =>  __('Back to Booking', 'hydra-booking'), 
            'Customer name' =>  __('Customer name', 'hydra-booking'), 
            'Jhon Deo' =>  __('Jhon Deo', 'hydra-booking'), 
            'Customer email' =>  __('Customer email', 'hydra-booking'), 
            'name@yourmail.com' =>  __('name@yourmail.com', 'hydra-booking'), 
            'Client Time zone' =>  __('Client Time zone', 'hydra-booking'), 
            'Select Time Zone' =>  __('Select Time Zone', 'hydra-booking'), 
            'Select Meeting' =>  __('Select Meeting', 'hydra-booking'), 
            'Select Your Meeting' =>  __('Select Your Meeting', 'hydra-booking'), 
            'Select Team Member' =>  __('Select Team Member', 'hydra-booking'), 
            'Select Location' =>  __('Select Location', 'hydra-booking'), 
            'Select Date' =>  __('Select Date', 'hydra-booking'), 
            'Enter schedule title' =>  __('Enter schedule title', 'hydra-booking'), 
            'Select Time' =>  __('Select Time', 'hydra-booking'), 
            'Select Booking Time' =>  __('Select Booking Time', 'hydra-booking'), 
            'Status' =>  __('Status', 'hydra-booking'), 
            'Select Booking status' =>  __('Select Booking status', 'hydra-booking'), 
            'Create Booking' =>  __('Create Booking', 'hydra-booking'), 
            'Has booked a meeting' =>  __('Has booked a meeting', 'hydra-booking'), 
            'Re-Booking' =>  __('Re-Booking', 'hydra-booking'), 
            'You are Re-book the booking:' =>  __('You are Re-book the booking:', 'hydra-booking'), 
            'Re-book' =>  __('Re-book', 'hydra-booking'), 
            'Select Status' =>  __('Select Status', 'hydra-booking'), 
            'Re-book Now' =>  __('Re-book Now', 'hydra-booking'), 
            'Select Time Slot' =>  __('Select Time Slot', 'hydra-booking'), 
            'Booking' =>  __('Booking', 'hydra-booking'), 
            

            'Delete' =>  __('Delete', 'hydra-booking'), 
            'Export as CSV' =>  __('Export as CSV', 'hydra-booking'), 
            'Add New Booking' =>  __('Add New Booking', 'hydra-booking'), 
            'Are you absolutely sure?' =>  __('Are you absolutely sure?', 'hydra-booking'), 
            'Data and bookings associated with this meeting will be deleted. It will not affect previously scheduled meetings.' =>  __('Data and bookings associated with this meeting will be deleted. It will not affect previously scheduled meetings.', 'hydra-booking'), 
            'Cancel' =>  __('Cancel', 'hydra-booking'),  
            'Export Bookings as CSV' =>  __('Export Bookings as CSV', 'hydra-booking'), 
            'Date Range' =>  __('Date Range', 'hydra-booking'), 
            'Select Date Range' =>  __('Select Date Range', 'hydra-booking'), 
            'From' =>  __('From', 'hydra-booking'), 
            'To' =>  __('To', 'hydra-booking'), 
            'Export Booking' =>  __('Export Booking', 'hydra-booking'), 
            'Host' =>  __('Host', 'hydra-booking'), 
            'Attendee' =>  __('Attendee', 'hydra-booking'), 
            'Meeting' =>  __('Meeting', 'hydra-booking'), 
            'Meeting Location' =>  __('Meeting Location', 'hydra-booking'), 
            'Date' =>  __('Date', 'hydra-booking'), 
            'Time' =>  __('Time', 'hydra-booking'),  
            'Date & Time' =>  __('Date & Time', 'hydra-booking'), 
            'Title' =>  __('Title', 'hydra-booking'),  
            'Duration' =>  __('Duration', 'hydra-booking'),  
            'Action' =>  __('Action', 'hydra-booking'), 
            'minutes' =>  __('minutes', 'hydra-booking'), 
            'Confirmed' =>  __('Confirmed', 'hydra-booking'), 
            'Pending' =>  __('Pending', 'hydra-booking'), 
            'Re-schedule' =>  __('Re-schedule', 'hydra-booking'), 
            'Canceled' =>  __('Canceled', 'hydra-booking'), 
            'Previous' =>  __('Previous', 'hydra-booking'), 
            'Next' =>  __('Next', 'hydra-booking'), 
            'No Booking Created' =>  __('No Booking Created', 'hydra-booking'), 
 
            'Your Previous Booking Time:' =>  __('Your Previous Booking Time:', 'hydra-booking'), 
            'Update Booking' =>  __('Update Booking', 'hydra-booking'), 
            'Meeting Details' =>  __('Meeting Details', 'hydra-booking'),   
            'Timezone' =>  __('Timezone', 'hydra-booking'), 
            'Durations' =>  __('Durations', 'hydra-booking'), 
            'Attendee Details' =>  __('Attendee Details', 'hydra-booking'), 
            'Booked At' =>  __('Booked At', 'hydra-booking'), 
            'Booking' =>  __('Booking', 'hydra-booking'), 
            'Timeframe:' =>  __('Timeframe:', 'hydra-booking'),  
            'Total Payment' =>  __('Total Payment', 'hydra-booking'),  
            'Mark as Complete' =>  __('Mark as Complete', 'hydra-booking'),  
            'Re-Schedule' =>  __('Re-Schedule', 'hydra-booking'),  
            "No, Don't cancel" =>  __("No, Don't cancel", "hydra-booking"),  
            "Yes, Cancel" =>  __("Yes, Cancel", "hydra-booking"),  
            'Cancel Meeting' =>  __('Cancel Meeting', 'hydra-booking'),  
            'Minutes' =>  __('Minutes', 'hydra-booking'),  
            'Google Meet' =>  __('Google Meet', 'hydra-booking'),  
            'Zoom' =>  __('Zoom', 'hydra-booking'),  
            'Internal Note' =>  __('Internal Note', 'hydra-booking'),  
            'Name' =>  __('Name', 'hydra-booking'),  
            'Activity Details' =>  __('Activity Details', 'hydra-booking'),  
            'N/A' =>  __('N/A', 'hydra-booking'),  
            // 'Delete' =>  __('Delete', 'hydra-booking'),  

            // Host
            'Hosts' =>  __('Hosts', 'hydra-booking'), 
            'Use existing availability' =>  __('Use existing availability', 'hydra-booking'), 
            'Custom availability' =>  __('Custom availability', 'hydra-booking'), 
            'Choose Schedule' =>  __('Choose Schedule', 'hydra-booking'),  
            'Availability title' =>  __('Availability title', 'hydra-booking'),  
            'Weekly hours' =>  __('Weekly hours', 'hydra-booking'), 
            'Add date overrides' =>  __('Add date overrides', 'hydra-booking'), 
            'Add dates when your availability changes from your daily hours' =>  __('Add dates when your availability changes from your daily hours', 'hydra-booking'), 
            'Availability' =>  __('Availability', 'hydra-booking'), 
            'Set up booking times when you are available' =>  __('Set up booking times when you are available', 'hydra-booking'), 
            'Add New Availability' =>  __('Add New Availability', 'hydra-booking'), 
            'Save & Continue' =>  __('Save & Continue', 'hydra-booking'), 
            
            'Before connecting make sure you provide the necessary credentials to' =>  __('Before connecting make sure you provide the necessary credentials to', 'hydra-booking'),  
            'Settings  Integrations' =>  __('Settings  Integrations', 'hydra-booking'), 
            'Change' =>  __('Change', 'hydra-booking'), 
            'Profile image' =>  __('Profile image', 'hydra-booking'), 
            'Cover image' =>  __('Cover image', 'hydra-booking'), 
            'Cover image is displayed in the meeting forms.' =>  __('Cover image is displayed in the meeting forms.', 'hydra-booking'), 
            'Recommended Image Size: 120x120px' =>  __('Recommended Image Size: 120x120px', 'hydra-booking'), 
            'General Information' =>  __('General Information', 'hydra-booking'), 
            'First name' =>  __('First name', 'hydra-booking'), 
            'Type your first name' =>  __('Type your first name', 'hydra-booking'), 
            'Last name' =>  __('Last name', 'hydra-booking'), 
            'Type your last name' =>  __('Type your last name', 'hydra-booking'), 
            'Email' =>  __('Email', 'hydra-booking'), 
            'Type your email' =>  __('Type your email', 'hydra-booking'), 
            'Time zone' =>  __('Time zone', 'hydra-booking'), 
            'Mobile' =>  __('Mobile', 'hydra-booking'), 
            'Type your mobile no' =>  __('Type your mobile no', 'hydra-booking'), 
            'Others Information' =>  __('Others Information', 'hydra-booking'),  
            'Deleting the host from settings will remove all data and bookings linked to this meeting. Previously scheduled meetings will not be impacted.' =>  __('Deleting the host from settings will remove all data and bookings linked to this meeting. Previously scheduled meetings will not be impacted.', 'hydra-booking'), 
            'Active' =>  __('Active', 'hydra-booking'), 
            'Disable' =>  __('Disable', 'hydra-booking'), 
            'Edit' =>  __('Edit', 'hydra-booking'), 
            'Profile' =>  __('Profile', 'hydra-booking'), 
            'Information' =>  __('Information', 'hydra-booking'), 
            'Calendars' =>  __('Calendars', 'hydra-booking'), 
            'Integrations' =>  __('Integrations', 'hydra-booking'), 
            'Add New Host' =>  __('Add New Host', 'hydra-booking'),  
            'Select User' =>  __('Select User', 'hydra-booking'), 
            'Username' =>  __('Username', 'hydra-booking'), 
            'Type Username' =>  __('Type Username', 'hydra-booking'),  
            'Type User Email' =>  __('Type User Email', 'hydra-booking'), 
            'Password' =>  __('Password', 'hydra-booking'), 
            'Type User Password' =>  __('Type User Password', 'hydra-booking'), 
            'Create Hosts' =>  __('Create Hosts', 'hydra-booking'), 
            'Not Connected' =>  __('Not Connected', 'hydra-booking'), 

            // Meetings
            'Meetings' =>  __('Meetings', 'hydra-booking'), 
            'Availability Range for this Booking' =>  __('Availability Range for this Booking', 'hydra-booking'), 
            'How many days can the invitee schedule?' =>  __('How many days can the invitee schedule?', 'hydra-booking'), 
            'Indefinitely into the future' =>  __('Indefinitely into the future', 'hydra-booking'), 
            'Meeting will be go for indefinitely into the future' =>  __('Meeting will be go for indefinitely into the future', 'hydra-booking'), 
            'Specific date range' =>  __('Specific date range', 'hydra-booking'), 
            'Meeting will be only available on specific dates' =>  __('Meeting will be only available on specific dates', 'hydra-booking'), 
            'Start' =>  __('Start', 'hydra-booking'), 
            'End' =>  __('End', 'hydra-booking'), 
            'Select Host' =>  __('Select Host', 'hydra-booking'), 
            'Create Host' =>  __('Create Host', 'hydra-booking'),   
            'Schedule Preview' =>  __('Schedule Preview', 'hydra-booking'), 
            'Unavailable' =>  __('Unavailable', 'hydra-booking'), 
            'Which hours are you free?' =>  __('Which hours are you free?', 'hydra-booking'), 
            'Mark unavailable (All day)' =>  __('Mark unavailable (All day)', 'hydra-booking'), 
            'Add override' =>  __('Add override', 'hydra-booking'), 
            'Add an override' =>  __('Add an override', 'hydra-booking'), 
            'Create One-to-One booking' =>  __('Create One-to-One booking', 'hydra-booking'), 
            'Create One-to-Group booking' =>  __('Create One-to-Group booking', 'hydra-booking'), 
            'Meeting title' =>  __('Meeting title', 'hydra-booking'), 
            'Type meeting title' =>  __('Type meeting title', 'hydra-booking'), 
            'Description' =>  __('Description', 'hydra-booking'), 
            'Describe about meeting' =>  __('Describe about meeting', 'hydra-booking'),  
            'Select Meetings Duration' =>  __('Select Meetings Duration', 'hydra-booking'), 
            'Type Custom Duration' =>  __('Type Custom Duration', 'hydra-booking'), 
            'Location' =>  __('Location', 'hydra-booking'), 
            'Address' =>  __('Address', 'hydra-booking'), 
            'Enter Address' =>  __('Enter Address', 'hydra-booking'), 
            'Add Custom Location' =>  __('Add Custom Location', 'hydra-booking'), 
            'Phone Number' =>  __('Phone Number', 'hydra-booking'), 
            'Enter Phone Number' =>  __('Enter Phone Number', 'hydra-booking'), 
            'Zoom is not connected.' =>  __('Zoom is not connected.', 'hydra-booking'), 
            'Please Configure' =>  __('Please Configure', 'hydra-booking'), 
            'Google Meet is not connected.' =>  __('Google Meet is not connected.', 'hydra-booking'), 
            'Add Another Location' =>  __('Add Another Location', 'hydra-booking'), 
            'Max invitees in a spot' =>  __('Max invitees in a spot', 'hydra-booking'), 
            'Display remaining spots on booking page' =>  __('Display remaining spots on booking page', 'hydra-booking'), 
            'Share' =>  __('Share', 'hydra-booking'), 
            'Details' =>  __('Details', 'hydra-booking'), 
            'Limits' =>  __('Limits', 'hydra-booking'), 
            'Questions' =>  __('Questions', 'hydra-booking'), 
            'Notifications' =>  __('Notifications', 'hydra-booking'), 
            'Payment' =>  __('Payment', 'hydra-booking'), 
            'Select Category' =>  __('Select Category', 'hydra-booking'), 
            'Create Category' =>  __('Create Category', 'hydra-booking'), 
            'Create Meeting Category' =>  __('Create Meeting Category', 'hydra-booking'), 
            'Category Title' =>  __('Category Title', 'hydra-booking'), 
            'Save Category' =>  __('Save Category', 'hydra-booking'), 
            'Webhook Integration' =>  __('Webhook Integration', 'hydra-booking'), 
            'Webhook integration enables automated data transfer between apps, allowing real-time communication and custom API interactions.' =>  __('Webhook integration enables automated data transfer between apps, allowing real-time communication and custom API interactions.', 'hydra-booking'), 
            'Add New Integrations' =>  __('Add New Integrations', 'hydra-booking'), 
            'Buffer time before meeting' =>  __('Buffer time before meeting', 'hydra-booking'), 
            'Buffer time after meeting' =>  __('Buffer time after meeting', 'hydra-booking'), 
            'Booking frequency' =>  __('Booking frequency', 'hydra-booking'), 
            'Limit how many times this meeting can be booked' =>  __('Limit how many times this meeting can be booked', 'hydra-booking'), 
            'Meeting interval' =>  __('Meeting interval', 'hydra-booking'), 
            'Default interval' =>  __('Default interval', 'hydra-booking'), 
            'Recurring Event' =>  __('Recurring Event', 'hydra-booking'), 
            'Set up a repeating schedule' =>  __('Set up a repeating schedule', 'hydra-booking'), 
            'Repeats every' =>  __('Repeats every', 'hydra-booking'), 
            'Maximum number of bookings' =>  __('Maximum number of bookings', 'hydra-booking'), 
            'Use meeting length (default)' =>  __('Use meeting length (default)', 'hydra-booking'), 
            'Attendee can cancel this meeting' =>  __('Attendee can cancel this meeting', 'hydra-booking'), 
            'Attendee can reschedule this meeting' =>  __('Attendee can reschedule this meeting', 'hydra-booking'), 
            'Filter' =>  __('Filter', 'hydra-booking'), 
            'All Host' =>  __('All Host', 'hydra-booking'), 
            'All Category' =>  __('All Category', 'hydra-booking'), 
            'Reset Filter' =>  __('Reset Filter', 'hydra-booking'), 
            'Create New Meeting' =>  __('Create New Meeting', 'hydra-booking'), 
            'One to One' =>  __('One to One', 'hydra-booking'), 
            'One host with one invitee. Good for: 1:1 interview, coffee chats' =>  __('One host with one invitee. Good for: 1:1 interview, coffee chats', 'hydra-booking'), 
            'Pro' =>  __('Pro', 'hydra-booking'), 
            'One to Group' =>  __('One to Group', 'hydra-booking'), 
            'One host with group of invitee. Good for: webinars, online clasess' =>  __('One host with group of invitee. Good for: webinars, online clasess', 'hydra-booking'), 
            'Booked' =>  __('Booked', 'hydra-booking'), 
            'Clone' =>  __('Clone', 'hydra-booking'), 
            'Preview' =>  __('Preview', 'hydra-booking'), 
            'No Meeting Created' =>  __('No Meeting Created', 'hydra-booking'), 
            'To Host' =>  __('To Host', 'hydra-booking'), 
            'To Attendee' =>  __('To Attendee', 'hydra-booking'), 
            'Booking Confirmation' =>  __('Booking Confirmation', 'hydra-booking'), 
            'Booking Pending' =>  __('Booking Pending', 'hydra-booking'), 
            'Send Email to Host' =>  __('Send Email to Host', 'hydra-booking'), 
            'Booking Cancel' =>  __('Booking Cancel', 'hydra-booking'), 
            'Booking Reschedule' =>  __('Booking Reschedule', 'hydra-booking'), 
            'Booking Reminder' =>  __('Booking Reminder', 'hydra-booking'), 
            'Send Email to Attendee' =>  __('Send Email to Attendee', 'hydra-booking'), 
            'Payment for this Meeting' =>  __('Payment for this Meeting', 'hydra-booking'), 
            'Securely process payment for this meeting using WooCommerce Payments, Stripe, or PayPal for a seamless transaction experience.' =>  __('Securely process payment for this meeting using WooCommerce Payments, Stripe, or PayPal for a seamless transaction experience.', 'hydra-booking'), 
            'Payment Method' =>  __('Payment Method', 'hydra-booking'), 
            'Payment ID' =>  __('Payment ID', 'hydra-booking'), 
            'Select Payment Method' =>  __('Select Payment Method', 'hydra-booking'), 
            'Woocommerce is not connected.' =>  __('Woocommerce is not connected.', 'hydra-booking'), 
            'Paypal is not connected.' =>  __('Paypal is not connected.', 'hydra-booking'), 
            'Stripe is not connected.' =>  __('Stripe is not connected.', 'hydra-booking'), 
            'Selecte Product' =>  __('Selecte Product', 'hydra-booking'), 
            'Price' =>  __('Price', 'hydra-booking'), 
            'Currency' =>  __('Currency', 'hydra-booking'), 
            'Save & Finish' =>  __('Save & Finish', 'hydra-booking'), 
            'Meeting Questions for Attendee' =>  __('Meeting Questions for Attendee', 'hydra-booking'), 
            'Create your own booking page questions' =>  __('Create your own booking page questions', 'hydra-booking'), 
            'Create custom form' =>  __('Create custom form', 'hydra-booking'), 
            'Use existing form' =>  __('Use existing form', 'hydra-booking'), 
            'Add more questions' =>  __('Add more questions', 'hydra-booking'), 
            'Add Question for Attendee' =>  __('Add Question for Attendee', 'hydra-booking'), 
            'Select Form Types' =>  __('Select Form Types', 'hydra-booking'), 
            'Select Form' =>  __('Select Form', 'hydra-booking'), 
            'Contact Form 7 is not connected.' =>  __('Contact Form 7 is not connected.', 'hydra-booking'), 
            'Fluent Forms is not connected.' =>  __('Fluent Forms is not connected.', 'hydra-booking'), 
            'Gravity Forms is not connected.' =>  __('Gravity Forms is not connected.', 'hydra-booking'), 
            'Add New Webhook' =>  __('Add New Webhook', 'hydra-booking'), 
            'Back' =>  __('Back', 'hydra-booking'), 
            'Upgrade to Pro' =>  __('Upgrade to Pro', 'hydra-booking'), 
            'Webhook URL' =>  __('Webhook URL', 'hydra-booking'), 
            'Type your Webhook URL' =>  __('Type your Webhook URL', 'hydra-booking'), 
            'Request Method' =>  __('Request Method', 'hydra-booking'), 
            'Request Format' =>  __('Request Format', 'hydra-booking'), 
            'Event Triggers' =>  __('Event Triggers', 'hydra-booking'), 
            'Request Header' =>  __('Request Header', 'hydra-booking'), 
            'Request Headers' =>  __('Request Headers', 'hydra-booking'), 
            'Header Key' =>  __('Header Key', 'hydra-booking'), 
            'Header Value' =>  __('Header Value', 'hydra-booking'), 
            'Request Body' =>  __('Request Body', 'hydra-booking'), 
            'Request Fields' =>  __('Request Fields', 'hydra-booking'), 
            'Enter Name' =>  __('Enter Name', 'hydra-booking'), 
            'Enter Value' =>  __('Enter Value', 'hydra-booking'), 
            'Enable this Webhook' =>  __('Enable this Webhook', 'hydra-booking'), 
            'Save Webhook' =>  __('Save Webhook', 'hydra-booking'), 

            // Settings
            'Settings' =>  __('Settings', 'hydra-booking'), 
            'Appearance' =>  __('Appearance', 'hydra-booking'), 
            'Set up your appearance settings for bookings' =>  __('Set up your appearance settings for bookings', 'hydra-booking'), 
            'View Documentation' =>  __('View Documentation', 'hydra-booking'), 
            'Custom brand colors' =>  __('Custom brand colors', 'hydra-booking'), 
            'Customize your own brand color into your booking page' =>  __('Customize your own brand color into your booking page', 'hydra-booking'), 
            'Primary Color' =>  __('Primary Color', 'hydra-booking'), 
            'Select Color' =>  __('Select Color', 'hydra-booking'), 
            'Secondary Color' =>  __('Secondary Color', 'hydra-booking'), 
            'Paragraph Color' =>  __('Paragraph Color', 'hydra-booking'), 
            'Typography' =>  __('Typography', 'hydra-booking'), 
            'Set your own typography for your brand' =>  __('Set your own typography for your brand', 'hydra-booking'), 
            'For title' =>  __('For title', 'hydra-booking'), 
            'Save' =>  __('Save', 'hydra-booking'), 
            'Meeting Category' =>  __('Meeting Category', 'hydra-booking'), 
            'Create and edit Meeting Category to organize your meetings.' =>  __('Create and edit Meeting Category to organize your meetings.', 'hydra-booking'), 
            'General Settings' =>  __('General Settings', 'hydra-booking'), 
            'Manage your time zone settings and bookings' =>  __('Manage your time zone settings and bookings', 'hydra-booking'), 
            'Date and Time' =>  __('Date and Time', 'hydra-booking'), 
            'Configure your date and time' =>  __('Configure your date and time', 'hydra-booking'), 
            'Admin Email' =>  __('Admin Email', 'hydra-booking'), 
            'Type your Admin Email' =>  __('Type your Admin Email', 'hydra-booking'), 
            'Time format' =>  __('Time format', 'hydra-booking'), 
            'Select Time Format' =>  __('Select Time Format', 'hydra-booking'), 
            'Week start from' =>  __('Week start from', 'hydra-booking'), 
            'Select country for phone code' =>  __('Select country for phone code', 'hydra-booking'), 
            'Select Country' =>  __('Select Country', 'hydra-booking'), 
            'Bookings' =>  __('Bookings', 'hydra-booking'), 
            'Manage your bookings and reservations' =>  __('Manage your bookings and reservations', 'hydra-booking'), 
            'Bookings will be completed automatically after' =>  __('Bookings will be completed automatically after', 'hydra-booking'), 
            'Minimum time required before Booking/Cancel/Reschedule' =>  __('Minimum time required before Booking/Cancel/Reschedule', 'hydra-booking'), 
            'Confirmed bookings by default.' =>  __('Confirmed bookings by default.', 'hydra-booking'), 
            'Confirmed reschedule by default.' =>  __('Confirmed reschedule by default.', 'hydra-booking'), 
            'Update General Settings' =>  __('Update General Settings', 'hydra-booking'), 
            'Host Settings' =>  __('Host Settings', 'hydra-booking'), 
            'Manage the settings and preferences for the hosts' =>  __('Manage the settings and preferences for the hosts', 'hydra-booking'), 
            'Information Builder' =>  __('Information Builder', 'hydra-booking'), 
            'Permissions' =>  __('Permissions', 'hydra-booking'), 
            'Update Host Settings' =>  __('Update Host Settings', 'hydra-booking'), 
            'Configure integration for conferencing, calendar and payment' =>  __('Configure integration for conferencing, calendar and payment', 'hydra-booking'), 
            'License Management' =>  __('License Management', 'hydra-booking'), 
            'Manage your HydraBooking Pro license' =>  __('Manage your HydraBooking Pro license', 'hydra-booking'), 
            'Unlock Advanced Capabilities with HydraBooking Pro !' =>  __('Unlock Advanced Capabilities with HydraBooking Pro !', 'hydra-booking'), 
            'Please upgrade to get all the advanced features.' =>  __('Please upgrade to get all the advanced features.', 'hydra-booking'), 
            'License Info' =>  __('License Info', 'hydra-booking'), 
            'Explore licensing options and benefits for advanced features.' =>  __('Explore licensing options and benefits for advanced features.', 'hydra-booking'), 
            'Valid' =>  __('Valid', 'hydra-booking'), 
            'Invalid' =>  __('Invalid', 'hydra-booking'), 
            'License Type' =>  __('License Type', 'hydra-booking'), 
            'License Expired on' =>  __('License Expired on', 'hydra-booking'), 
            'Renew' =>  __('Renew', 'hydra-booking'), 
            'Support Expired on' =>  __('Support Expired on', 'hydra-booking'), 
            'Your License Key' =>  __('Your License Key', 'hydra-booking'), 
            'Deactivate' =>  __('Deactivate', 'hydra-booking'), 
            'Confirm License Deactivation!' =>  __('Confirm License Deactivation!', 'hydra-booking'), 
            'Deactivating the license will remove access to all premium features.' =>  __('Deactivating the license will remove access to all premium features.', 'hydra-booking'), 
            'License Key' =>  __('License Key', 'hydra-booking'), 
            'Enter your License key' => __('Enter your License key', 'hydra-booking'),
            'Insert your license key here. You can get it from our Client Portal -> Support -> License keys.' =>  __('Insert your license key here. You can get it from our Client Portal -> Support -> License keys.', 'hydra-booking'), 
            'License Email' =>  __('License Email', 'hydra-booking'), 
            'Please enter the email address you used for purchasing the plugin.' =>  __('Please enter the email address you used for purchasing the plugin.', 'hydra-booking'), 
            'Activate' =>  __('Activate', 'hydra-booking'), 
            'Organize booking confirmation/cancel/reschedule/reminder notification for host and attendee' =>  __('Organize booking confirmation/cancel/reschedule/reminder notification for host and attendee', 'hydra-booking'), 
            'Send Email to Host for Booking Pending' =>  __('Send Email to Host for Booking Pending', 'hydra-booking'), 
            'Send Email to Host for Booking Cancels' =>  __('Send Email to Host for Booking Cancels', 'hydra-booking'), 
            'General' =>  __('General', 'hydra-booking'), 
            'All' =>  __('All', 'hydra-booking'), 
            'Conference' =>  __('Conference', 'hydra-booking'), 
            'Payments' =>  __('Payments', 'hydra-booking'), 
            'Marketing Tools' =>  __('Marketing Tools', 'hydra-booking'), 
            'Forms' =>  __('Forms', 'hydra-booking'), 
            'License' =>  __('License', 'hydra-booking'), 
            'Frontend Dashboard' =>  __('Frontend Dashboard', 'hydra-booking'), 
            'Frontend Dashboard Settings' =>  __('Frontend Dashboard Settings', 'hydra-booking'), 
            'Select Color Palette for Dashboard' =>  __('Select Color Palette for Dashboard', 'hydra-booking'), 
            'Customize your brand colors for the Frontend Dashboard.' =>  __('Customize your brand colors for the Frontend Dashboard.', 'hydra-booking'), 
            'Manage the settings and preferences for the frontend dashboard' =>  __('Manage the settings and preferences for the frontend dashboard', 'hydra-booking'), 
            'Signup' =>  __('Signup', 'hydra-booking'), 
            'LogIn' =>  __('LogIn', 'hydra-booking'), 
            'Manage the general settings and preferences for the frontend dashboard' =>  __('Manage the general settings and preferences for the frontend dashboard', 'hydra-booking'), 
            'Dashboard Logo' =>  __( 'Dashboard Logo', 'hydra-booking'),
            'Mobile Logo' =>  __('Mobile Logo', 'hydra-booking'), 
            'This logo is used for the mobile version of the dashboard' =>  __('This logo is used for the mobile version of the dashboard', 'hydra-booking'), 
            'This logo serves as the main header image of the dashboard' =>  __('This logo serves as the main header image of the dashboard', 'hydra-booking'), 
            'Signup Page Settings' =>  __('Signup Page Settings', 'hydra-booking'), 
            'Customize the settings for the signup page' =>  __('Customize the settings for the signup page', 'hydra-booking'), 
            'Choose a page that will be used as the Registration Page.' =>  __('Choose a page that will be used as the Registration Page.', 'hydra-booking'), 
            'Registration Page' =>  __('Registration Page', 'hydra-booking'), 
            'Select the destination for users after they register.' =>  __('Select the destination for users after they register.', 'hydra-booking'), 
            'Choose your Page' =>  __('Choose your Page', 'hydra-booking'), 
            'Select the destination page for users after they log in.' =>  __('Select the destination page for users after they log in.', 'hydra-booking'), 
            'Login Page Settings' =>  __('Login Page Settings', 'hydra-booking'), 
            'Customize the settings for the login page' =>  __('Customize the settings for the login page', 'hydra-booking'), 
            'Choose a page to serve as the Login Page.' =>  __('Choose a page to serve as the Login Page.', 'hydra-booking'), 
            'Login Page' =>  __('Login Page', 'hydra-booking'), 
            'Select Login Page' =>  __('Select Login Page', 'hydra-booking'), 
            'Select the destination for users after they log in.' =>  __('Select the destination for users after they log in.', 'hydra-booking'), 
            'Login Redirect Option' =>  __('Login Redirect Option', 'hydra-booking'), 
            'Select Login Redirect Option' =>  __('Select Login Redirect Option', 'hydra-booking'),  
            'Logo preference' =>  __('Logo preference', 'hydra-booking'),  
            'JPG, JPEG, PNG. Max 5 MB.' =>  __('JPG, JPEG, PNG. Max 5 MB.', 'hydra-booking'),  
            'Choose images or drag & drop it here.' =>  __('Choose images or drag & drop it here.', 'hydra-booking'),  
            'This only applies to your Frontend Dashboard.' =>  __('This only applies to your Frontend Dashboard.', 'hydra-booking'),  
            'Color Palette for Dashboard' =>  __('Color Palette for Dashboard', 'hydra-booking'),  
            'Default Palette' =>  __('Default Palette', 'hydra-booking'),  
            'Custom Palette' =>  __('Custom Palette', 'hydra-booking'),  
            'Primary Color (Default)' =>  __('Primary Color (Default)', 'hydra-booking'),  
            'Primary Color (Hover)' =>  __('Primary Color (Hover)', 'hydra-booking'),  
            'Secondary Color (Default)' =>  __('Secondary Color (Default)', 'hydra-booking'),  
            'Secondary Color (Hover)' =>  __('Secondary Color (Hover)', 'hydra-booking'),  
            'Text Color (Title)' =>  __('Text Color (Title)', 'hydra-booking'),  
            'Text Color (Paragraph)' =>  __('Text Color (Paragraph)', 'hydra-booking'),  
            'Surface Color (Primary)' =>  __('Surface Color (Primary)', 'hydra-booking'),  
            'Surface Color (Background)' =>  __('Surface Color (Background)', 'hydra-booking'),  
            'Surface Color (Border)' =>  __('Surface Color (Border)', 'hydra-booking'),  
            'Surface Color (Border Hover)' =>  __('Surface Color (Border Hover)', 'hydra-booking'),  
            'Surface Color (Input Field)' =>  __('Surface Color (Input Field)', 'hydra-booking'),  
            'Use shortcode [hydra_signup_form] to show Sign up form in post/page/widget.' =>  __('Use shortcode [hydra_signup_form] to show Sign up form in post/page/widget.', 'hydra-booking'),  
            'Sign up Title' =>  __('Sign up Title', 'hydra-booking'),  
            'Sign up Sub-title' =>  __('Sign up Sub-title', 'hydra-booking'),  
            'Sign up Page' =>  __('Sign up Page', 'hydra-booking'),    
            'Enable Email Verification' =>  __('Enable Email Verification', 'hydra-booking'),  
            'Use shortcode [hydra_login_form] to show login form in post/page/widget.' =>  __('Use shortcode [hydra_login_form] to show login form in post/page/widget.', 'hydra-booking'),  
            'Login Title' =>  __('Login Title', 'hydra-booking'),  
            'Login Sub-title' =>  __('Login Sub-title', 'hydra-booking'),  
            'Upload logo' =>  __('Upload logo', 'hydra-booking'),  
            'Upload Responsive logo' =>  __('Upload Responsive logo', 'hydra-booking'),  
            'Type login sub-title' =>  __('Type login sub-title', 'hydra-booking'),  
            'Header Background' =>  __('Header Background', 'hydra-booking'),  
            // 'License' =>  __('License', 'hydra-booking'),  
            // 'License' =>  __('License', 'hydra-booking'),  



            // Frontend Dashboard : 
            'Hi,' =>  __('Hi,', 'hydra-booking'),
            'My Account' =>  __('My Account', 'hydra-booking'),
            // 'Hi' =>  __('Hi', 'hydra-booking'), 
            // 'Hi' =>  __('Hi', 'hydra-booking'),
            'Select Currency' =>  __('Select Currency', 'hydra-booking'), 

            // Quick Setup
            'Welcome to HydraBooking!' =>  __('Welcome to HydraBooking!', 'hydra-booking'), 
            'Thank you for choosing HydraBooking, the premier solution for effortless appointment and booking scheduling' =>  __('Thank you for choosing HydraBooking, the premier solution for effortless appointment and booking scheduling', 'hydra-booking'), 
            'Enter your email' =>  __('Enter your email', 'hydra-booking'), 
            'Receive updates and promotions' =>  __('Receive updates and promotions', 'hydra-booking'), 
            'Get Started in a Minute' =>  __('Get Started in a Minute', 'hydra-booking'), 
            'Congratulations! You are All Set Up!' =>  __('Congratulations! You are All Set Up!', 'hydra-booking'), 
            'You have successfully installed and activated Hydrabooking, configured your settings, connected your calendar, customized your booking forms, and embedded them on your website.' =>  __('You have successfully installed and activated Hydrabooking, configured your settings, connected your calendar, customized your booking forms, and embedded them on your website.', 'hydra-booking'), 
            'All Integrations' =>  __('All Integrations', 'hydra-booking'), 
            'Visit Dashboard' =>  __('Visit Dashboard', 'hydra-booking'), 
            'Your Meeting is ready!' =>  __('Your Meeting is ready!', 'hydra-booking'), 
            'Simplify Your Work with HydraBooking' =>  __('Simplify Your Work with HydraBooking', 'hydra-booking'), 
            'Our intuitive setup process makes HydraBooking a breeze to use, even for non-technical users.' =>  __('Our intuitive setup process makes HydraBooking a breeze to use, even for non-technical users.', 'hydra-booking'), 
            'Your business type?' =>  __('Your business type?', 'hydra-booking'), 
            'Skip' =>  __('Skip', 'hydra-booking'), 
            'Experience HydraBooking in Action (Instantly!)' =>  __('Experience HydraBooking in Action (Instantly!)', 'hydra-booking'), 
            'It helps you customize the booking process to fit your workflow and make things run more smoothly.' =>  __('It helps you customize the booking process to fit your workflow and make things run more smoothly.', 'hydra-booking'), 
            'Create demo meeting' =>  __('Create demo meeting', 'hydra-booking'), 
            'Take control of your schedule' =>  __('Take control of your schedule', 'hydra-booking'), 
            'Make your appointment booking process even easier by simply setting your availability.' =>  __('Make your appointment booking process even easier by simply setting your availability.', 'hydra-booking'), 
            'You’re currently using HydraBooking in limited mode. To access advanced features, provide your license key now!' => __('You’re currently using HydraBooking in limited mode. To access advanced features, provide your license key now!', 'hydra-booking'),
            'Let’s Get Started!' => __('Let’s Get Started!', 'hydra-booking'),
            'Enter your email address' => __('Enter your email address', 'hydra-booking'),
            'Unlock this Feature' => __('Unlock this Feature', 'hydra-booking'),
            'Please provide your email address. We’ll send your key directly to your inbox.' => __('Please provide your email address. We’ll send your key directly to your inbox.', 'hydra-booking'),
            'Send me the License key' => __('Send me the License key', 'hydra-booking'),
            'Please enter a valid email address.' => __('Please enter a valid email address.', 'hydra-booking'),
            'Perfect' => __('Perfect', 'hydra-booking'),
            'Create a Free License Key' => __('Create a Free License Key', 'hydra-booking'),
            'Please Install the HydraBooking Pro !' => __("Please Install the HydraBooking Pro !", 'hydra-booking'),
            'You already activated the HydraBooking Pro License, Install the Hydra Booking Pro Plugin.' => __("You already activated the HydraBooking Pro License, Install the Hydra Booking Pro Plugin.", 'hydra-booking'),
            'Already used!' => __('Already used!', 'hydra-booking'),
            'You already used this email. Use another email address or click on the following link to obtain the previous license key.' => __('You already used this email. Use another email address or click on the following link to obtain the previous license key.', 'hydra-booking'),
            'Check your inbox and set a password for your security then paste the license key below.' => __('Check your inbox and set a password for your security then paste the license key below.', 'hydra-booking'),
            'Sent successfully!' => __('Sent successfully!', 'hydra-booking'),
            'Unlock Features' => __('Unlock Features', 'hydra-booking'),

            // Component : availability 
            'Mark as read' =>  __('Mark as read', 'hydra-booking'), 
            'Save Availability' =>  __('Save Availability', 'hydra-booking'), 
            'Update Availability' =>  __('Update Availability', 'hydra-booking'), 
            'Default' =>  __('Default', 'hydra-booking'), 

            // Component : hosts
            'Apple Calendar' =>  __('Apple Calendar', 'hydra-booking'), 
            'New standard in online payment' =>  __('New standard in online payment', 'hydra-booking'), 
            'Enable the calendars you want to check for conflicts to prevent double bookings.' =>  __('Enable the calendars you want to check for conflicts to prevent double bookings.', 'hydra-booking'), 
            'Apple ID (Email)' =>  __('Apple ID (Email)', 'hydra-booking'), 
            'Enter Apple ID (Email)' =>  __('Enter Apple ID (Email)', 'hydra-booking'), 
            'App Specific Password' =>  __('App Specific Password', 'hydra-booking'), 
            'Enter App Specific Password' =>  __('Enter App Specific Password', 'hydra-booking'), 
            'Google Calendar/Meet' =>  __('Google Calendar/Meet', 'hydra-booking'), 
            'Connect your Google Calendar/Meet to sync your booked events.' =>  __('Connect your Google Calendar/Meet to sync your booked events.', 'hydra-booking'), 
            'Go To Settings' =>  __('Go To Settings', 'hydra-booking'), 
            'Settings' =>  __('Settings', 'hydra-booking'), 
            'Get Access Token' =>  __('Get Access Token', 'hydra-booking'), 
            'Google Calendar' =>  __('Google Calendar', 'hydra-booking'), 
            'Outlook Calendar' =>  __('Outlook Calendar', 'hydra-booking'), 
            'Connect your Outlook Calendar to sync your booked events.' =>  __('Connect your Outlook Calendar to sync your booked events.', 'hydra-booking'), 
            'Upcoming' =>  __('Upcoming', 'hydra-booking'), 
            'Completed' =>  __('Completed', 'hydra-booking'), 
            'Latest' =>  __('Latest', 'hydra-booking'), 
            'Events' =>  __('Events', 'hydra-booking'), 
            'Attendees' =>  __('Attendees', 'hydra-booking'), 
            'Type' =>  __('Type', 'hydra-booking'), 
            'Zoho' =>  __('Zoho', 'hydra-booking'), 
            'Connect' =>  __('Connect', 'hydra-booking'), 
            'Connect Your Zoho Account' =>  __('Connect Your Zoho Account', 'hydra-booking'), 
            'Please read the documentation here for step by step guide to know how you can get api credentials from Zoho Account' =>  __('Please read the documentation here for step by step guide to know how you can get api credentials from Zoho Account', 'hydra-booking'), 
            'Zoho Client ID' =>  __('Zoho Client ID', 'hydra-booking'), 
            'Enter Your Client ID' =>  __('Enter Your Client ID', 'hydra-booking'), 
            'Zoho Client Secret' =>  __('Zoho Client Secret', 'hydra-booking'), 
            'Enter Your Client Secret' =>  __('Enter Your Client Secret', 'hydra-booking'), 
            'Zoho Redirect URL' =>  __('Zoho Redirect URL', 'hydra-booking'), 
            'Enter Your Redirect URL' =>  __('Enter Your Redirect URL', 'hydra-booking'), 
            'Save & Validate' =>  __('Save & Validate', 'hydra-booking'), 
            'Shortcode' =>  __('Shortcode', 'hydra-booking'), 
            'Shortcodes' =>  __('Shortcodes', 'hydra-booking'), 
            'Shortcodes Settings' =>  __('Shortcodes Settings', 'hydra-booking'), 
            'Manage and customize your shortcodes for Hydrabooking.' =>  __('Manage and customize your shortcodes for Hydrabooking.', 'hydra-booking'), 
            'Meetings Shortcode' =>  __('Meetings Shortcode', 'hydra-booking'), 
            'Generate a shortcode to embed your meetings on your website.' =>  __('Generate a shortcode to embed your meetings on your website.', 'hydra-booking'), 
            'Shortcode title' =>  __('Shortcode title', 'hydra-booking'), 
            'Shortcode sub-title' =>  __('Shortcode sub-title', 'hydra-booking'), 
            'Type a title for your shortcode' =>  __('Type a title for your shortcode', 'hydra-booking'), 
            'Type a sub-title for your shortcode' =>  __('Type a sub-title for your shortcode', 'hydra-booking'), 
            'Select meeting category' =>  __('Select meeting category', 'hydra-booking'), 
            'Sort By' =>  __('Sort By', 'hydra-booking'), 
            'Order By' =>  __('Order By', 'hydra-booking'), 
            'Reset' =>  __('Reset', 'hydra-booking'), 
            'Generate' =>  __('Generate', 'hydra-booking'), 
            'Display Limit' =>  __('Display Limit', 'hydra-booking'), 
            'Meeting category : All' =>  __('Meeting category : All', 'hydra-booking'), 
            'Select host : All' =>  __('Select host : All', 'hydra-booking'), 
            'Hosts Shortcode' =>  __('Hosts Shortcode', 'hydra-booking'), 
            'Generate a shortcode to embed your meeting hosts list on your website.' =>  __('Generate a shortcode to embed your meeting hosts list on your website.', 'hydra-booking'), 
            'Categories Shortcode' =>  __('Categories Shortcode', 'hydra-booking'), 
            'Generate a shortcode to embed your meetings categories list on your website.' =>  __('Generate a shortcode to embed your meetings categories list on your website.', 'hydra-booking'), 
            'Meeting Categories' =>  __('Meeting Categories', 'hydra-booking'), 
            'Export as .ics' =>  __('Export as .ics', 'hydra-booking'), 
            'Download as .ics' =>  __('Download as .ics', 'hydra-booking'), 
            'More' =>  __('More', 'hydra-booking'), 
            'Embed code' =>  __('Embed code', 'hydra-booking'), 
            'Copy Link' =>  __('Copy Link', 'hydra-booking'), 

            // Component : integrations
            'Contact Form 7' =>  __('Contact Form 7', 'hydra-booking'), 
            'Install and enable Contact Form 7 for meeting forms.' =>  __('Install and enable Contact Form 7 for meeting forms.', 'hydra-booking'), 
            'Fluent CRM' =>  __('Fluent CRM', 'hydra-booking'), 
            'Integrate FluentCRM to manage and track customer data easily.' =>  __('Integrate FluentCRM to manage and track customer data easily.', 'hydra-booking'), 
            'Fluent Forms' =>  __('Fluent Forms', 'hydra-booking'), 
            'Install and enable Fluent Forms for meeting forms.' =>  __('Install and enable Fluent Forms for meeting forms.', 'hydra-booking'), 
            'Forminator' =>  __('Forminator', 'hydra-booking'), 
            'Install and enable Forminator for meeting forms.' =>  __('Install and enable Forminator for meeting forms.', 'hydra-booking'), 
            'Connect Google Calendar/Meet API to add events and create video calls.' =>  __('Connect Google Calendar/Meet API to add events and create video calls.', 'hydra-booking'), 
            'Add Google Calendar' =>  __('Add Google Calendar', 'hydra-booking'), 
            'Please read the documentation here for step by step guide to know how you can get api credentials from Google Calendar' =>  __('Please read the documentation here for step by step guide to know how you can get api credentials from Google Calendar', 'hydra-booking'), 
            'Client ID' =>  __('Client ID', 'hydra-booking'), 
            'Enter Client ID' =>  __('Enter Client ID', 'hydra-booking'), 
            'Secret Key' =>  __('Secret Key', 'hydra-booking'), 
            'Enter Secret Key' =>  __('Enter Secret Key', 'hydra-booking'), 
            'Redirect Url' =>  __('Redirect Url', 'hydra-booking'), 
            'Enter Redirect Url' =>  __('Enter Redirect Url', 'hydra-booking'), 
            'Copy URL' =>  __('Copy URL', 'hydra-booking'), 
            'Gravity Forms' =>  __('Gravity Forms', 'hydra-booking'), 
            'Install and enable Gravity Forms for meeting forms.' =>  __('Install and enable Gravity Forms for meeting forms.', 'hydra-booking'), 
            'Mailchimp' =>  __('Mailchimp', 'hydra-booking'), 
            'Integrate Mailchimp API to collect attendee emails and info.' =>  __('Integrate Mailchimp API to collect attendee emails and info.', 'hydra-booking'), 
            'Please read the documentation here for step by step guide to know how you can get api credentials from Mailchimp Account' =>  __('Please read the documentation here for step by step guide to know how you can get api credentials from Mailchimp Account', 'hydra-booking'), 
            'Mailchimp API Key' =>  __('Mailchimp API Key', 'hydra-booking'), 
            'Enter Your API Key' =>  __('Enter Your API Key', 'hydra-booking'), 
            'Connect Outlook Calendar/Teams API for event creation.' =>  __('Connect Outlook Calendar/Teams API for event creation.', 'hydra-booking'), 
            'Please read the documentation here for step by step guide to know how you can get api credentials from Outlook Calendar' =>  __('Please read the documentation here for step by step guide to know how you can get api credentials from Outlook Calendar', 'hydra-booking'), 
            'PayPal' =>  __('PayPal', 'hydra-booking'), 
            'Connect PayPal API for easy online payment solutions.' =>  __('Connect PayPal API for easy online payment solutions.', 'hydra-booking'), 
            'Connect Your Paypal Account' =>  __('Connect Your Paypal Account', 'hydra-booking'), 
            'Please read the documentation here for step by step guide to know how you can get api credentials from Paypal Account' =>  __('Please read the documentation here for step by step guide to know how you can get api credentials from Paypal Account', 'hydra-booking'), 
            'Environment' =>  __('Environment', 'hydra-booking'), 
            'Paypal Client ID' =>  __('Paypal Client ID', 'hydra-booking'), 
            'Paypal Secret Key' =>  __('Paypal Secret Key', 'hydra-booking'), 
            'Enter Your Paypal Secret' =>  __('Enter Your Paypal Secret', 'hydra-booking'), 
            'Stripe' =>  __('Stripe', 'hydra-booking'), 
            'Integrate Stripe API for secure payment processing.' =>  __('Integrate Stripe API for secure payment processing.', 'hydra-booking'), 
            'Connect Your Stripe Account' =>  __('Connect Your Stripe Account', 'hydra-booking'), 
            'Please read the documentation here for step by step guide to know how you can get api credentials from Stripe Account' =>  __('Please read the documentation here for step by step guide to know how you can get api credentials from Stripe Account', 'hydra-booking'), 
            'Stripe Public Key' =>  __('Stripe Public Key', 'hydra-booking'), 
            'Enter Your Public Key' =>  __('Enter Your Public Key', 'hydra-booking'), 
            'Stripe Secret Key' =>  __('Stripe Secret Key', 'hydra-booking'), 
            'Enter Your Stripe Secret' =>  __('Enter Your Stripe Secret', 'hydra-booking'), 
            'Webhook' =>  __('Webhook', 'hydra-booking'), 
            'Set up webhook integration to send data via custom API.' =>  __('Set up webhook integration to send data via custom API.', 'hydra-booking'), 
            'Woo Payment' =>  __('Woo Payment', 'hydra-booking'), 
            'Connect WooCommerce for manage booking payment.' =>  __('Connect WooCommerce for manage booking payment.', 'hydra-booking'), 
            'Connected' =>  __('Connected', 'hydra-booking'), 
            'Zoho CRM' =>  __('Zoho CRM', 'hydra-booking'), 
            'Implement Zoho CRM for comprehensive sales and marketing automation.' =>  __('Implement Zoho CRM for comprehensive sales and marketing automation.', 'hydra-booking'), 
            'Zoom' =>  __('Zoom', 'hydra-booking'), 
            'Connect Zoom API to configure virtual meetings.' =>  __('Connect Zoom API to configure virtual meetings.', 'hydra-booking'), 
            'Add New Zoom User Account' =>  __('Add New Zoom User Account', 'hydra-booking'), 
            'Please read the documentation here for step by step guide to know how you can get api credentials from Zoom Account' =>  __('Please read the documentation here for step by step guide to know how you can get api credentials from Zoom Account', 'hydra-booking'), 
            'Zoom Account ID' =>  __('Zoom Account ID', 'hydra-booking'), 
            'Enter Your Account ID' =>  __('Enter Your Account ID', 'hydra-booking'), 
            'Zoom App Client ID' =>  __('Zoom App Client ID', 'hydra-booking'), 
            'Enter Your App Client ID' =>  __('Enter Your App Client ID', 'hydra-booking'), 
            'Zoom App Secret Key' =>  __('Zoom App Secret Key', 'hydra-booking'), 
            'Enter Your App Secret Key' =>  __('Enter Your App Secret Key', 'hydra-booking'), 
            'Telegram' => __('Telegram', 'hydra-booking'),
            'Connect Telegram API to configure virtual meetings.' => __('Connect Telegram API to configure virtual meetings.', 'hydra-booking'),
            'Add New Telegram Option' => __('Add New Telegram Option', 'hydra-booking'),
            'Please read the documentation here for step by step guide to know how you can get BOT Token and Chat ID from Telegram Account' => __('Please read the documentation here for step by step guide to know how you can get BOT Token and Chat ID from Telegram Account', 'hydra-booking'),
            'Telegram BOT Token' => __('Telegram BOT Token', 'hydra-booking'),
            'Enter Your Telegram BOT Token' => __('Enter Your Telegram BOT Token', 'hydra-booking'),
            'Telegram Chat ID' => __('Telegram Chat ID', 'hydra-booking'),
            'Enter Your Telegram Chat ID' => __('Enter Your Telegram Chat ID', 'hydra-booking'),
            'Whatsapp' => __('Whatsapp', 'hydra-booking'),
            'Connect Whatsapp API to configure virtual meetings.' => __('Connect Whatsapp API to configure virtual meetings.', 'hydra-booking'),
            'Add Whatsapp Option' => __('Add Whatsapp Option', 'hydra-booking'),
            'Please read the documentation here for step by step guide to know how you can get Access Token from Whatsapp Account' => __('Please read the documentation here for step by step guide to know how you can get Access Token from Whatsapp Account', 'hydra-booking'),
            'Whatsapp Number' => __('Whatsapp Number', 'hydra-booking'),
            'Enter Your Whatsapp Number' => __('Enter Your Whatsapp Number', 'hydra-booking'),
            'Access Token' => __('Access Token', 'hydra-booking'),
            'Enter Your Access Token' => __('Enter Your Access Token', 'hydra-booking'),
            'Twilio' => __('Twilio', 'hydra-booking'),
            'Connect Twilio API to configure virtual meetings.' => __('Connect Twilio API to configure virtual meetings.', 'hydra-booking'),
            'Add Twilio Option' => __('Add Twilio Option', 'hydra-booking'),
            'Please read the documentation here for step by step guide to know how you can get Access Token from Twilio Account' => __('Please read the documentation here for step by step guide to know how you can get Access Token from Twilio Account', 'hydra-booking'),
            'Account SID' => __('Account SID', 'hydra-booking'),
            'Enter Your Account SID' => __('Enter Your Account SID', 'hydra-booking'),
            'From Number' => __('From Number', 'hydra-booking'),
            'Enter Your From Number' => __('Enter Your From Number', 'hydra-booking'),
            'Receiver Number' => __('Receiver Number', 'hydra-booking'),
            'Enter Your Receiver Number' => __('Enter Your Receiver Number', 'hydra-booking'),
            'Slack' => __('Slack', 'hydra-booking'),
            'Connect Slack API to configure virtual meetings.' => __('Connect Slack API to configure virtual meetings.', 'hydra-booking'),
            'Add Slack Option' => __('Add Slack Option', 'hydra-booking'),
            'Please read the documentation here for step by step guide to know how you can get Access Token from Slack Account' => __('Please read the documentation here for step by step guide to know how you can get Access Token from Slack Account', 'hydra-booking'),
            'Channel Name' => __('Channel Name', 'hydra-booking'),
            'Enter Your Channel Name' => __('Enter Your Channel Name', 'hydra-booking'),


            // Component : meetings
            'Integration' =>  __('Integration', 'hydra-booking'), 
            'Integrate Mailchimp, FluentCRM, and Zoho for managing emails, tracking leads, and enhancing customer engagement.' =>  __('Integrate Mailchimp, FluentCRM, and Zoho for managing emails, tracking leads, and enhancing customer engagement.', 'hydra-booking'), 
            'Integrations Title' =>  __('Integrations Title', 'hydra-booking'), 
            'Type your Integrations Title' =>  __('Type your Integrations Title', 'hydra-booking'), 
            'Select Audience' =>  __('Select Audience', 'hydra-booking'), 
            'FluentCRM Lists' =>  __('FluentCRM Lists', 'hydra-booking'), 
            'Select FluentCRM List' =>  __('Select FluentCRM List', 'hydra-booking'), 
            'Contact Tags' =>  __('Contact Tags', 'hydra-booking'), 
            'Select Contact Tag' =>  __('Select Contact Tag', 'hydra-booking'), 
            'Modules' =>  __('Modules', 'hydra-booking'), 
            'Select Modules' =>  __('Select Modules', 'hydra-booking'), 
            'Select integrations' =>  __('Select integrations', 'hydra-booking'), 
            'Mailchimp is not connected.' =>  __('Mailchimp is not connected.', 'hydra-booking'), 
            'ZohoCRM is not connected.' =>  __('ZohoCRM is not connected.', 'hydra-booking'), 
            'Share link' =>  __('Share link', 'hydra-booking'), 
            'Short code' =>  __('Short code', 'hydra-booking'), 
            'Copy Code' =>  __('Copy Code', 'hydra-booking'), 

            // 
            'Select Template' =>  __('Select Template', 'hydra-booking'), 
            'Enter From Email' =>  __('Enter From Email', 'hydra-booking'), 
            'Enter Mail Subject' =>  __('Enter Mail Subject', 'hydra-booking'), 
            'Subject' =>  __('Subject', 'hydra-booking'), 
            'Mail Body' =>  __('Mail Body', 'hydra-booking'), 
            'Update' =>  __('Update', 'hydra-booking'),
            'Greetings' => __('Greetings', 'hydra-booking'), 
            'Buttons'  => __('Buttons', 'hydra-booking'),

            // Activity Logs
            'Booking has been completed' =>  __('Booking has been completed', 'hydra-booking'), 
            'Confirmation Email Sent' =>  __('Confirmation Email Sent', 'hydra-booking'), 
            'Confirmation Email Sent to Host' =>  __('Confirmation Email Sent to Host', 'hydra-booking'), 
            'Confirmation Email Sent to Attendee' =>  __('Confirmation Email Sent to Attendee', 'hydra-booking'), 
            'Pending Email Sent' =>  __('Pending Email Sent', 'hydra-booking'), 
            'Pending Email Sent to Host' =>  __('Pending Email Sent to Host', 'hydra-booking'), 
            'Pending Email Sent to Attendee' =>  __('Pending Email Sent to Attendee', 'hydra-booking'), 
            'Canceled Email Sent' =>  __('Canceled Email Sent', 'hydra-booking'), 
            'Canceled Email Sent to Host' =>  __('Canceled Email Sent to Host', 'hydra-booking'), 
            'Canceled Email Sent to Attendee' =>  __('Canceled Email Sent to Attendee', 'hydra-booking'), 
            'ReSchedule Email Sent' =>  __('ReSchedule Email Sent', 'hydra-booking'), 
            'ReSchedule Email Sent to Host' =>  __('ReSchedule Email Sent to Host', 'hydra-booking'), 
            'ReSchedule Email Sent to Attendee' =>  __('ReSchedule Email Sent to Attendee', 'hydra-booking'), 
            'Reminder Email Sent' =>  __('Reminder Email Sent', 'hydra-booking'), 
            'Reminder Email Sent to Attendee' =>  __('Reminder Email Sent to Attendee', 'hydra-booking'), 
            'Booking Has Been Confirmed' =>  __('Booking Has Been Confirmed', 'hydra-booking'),  
            'Booking Has Been Pending' =>  __('Booking Has Been Pending', 'hydra-booking'), 
            'Booking Has Been Canceled' =>  __('Booking Has Been Canceled', 'hydra-booking'), 
            'Booking Has Been Rescheduled' =>  __('Booking Has Been Rescheduled', 'hydra-booking'),  

            //
            'Import bookings from a CSV file' =>  __('Import bookings from a CSV file', 'hydra-booking'), 
            'This tool allows you to import or merge booking data to your store from a CSV file.' =>  __('This tool allows you to import or merge booking data to your store from a CSV file.', 'hydra-booking'), 
            'Map CSV fields to Booking' =>  __('Map CSV fields to Booking', 'hydra-booking'), 
            'elect fields from your CSV file to map against booking fields, or to ignore during import.' =>  __('elect fields from your CSV file to map against booking fields, or to ignore during import.', 'hydra-booking'), 
            'Run The Import' =>  __('Run The Import', 'hydra-booking'), 
            'Create and customize the information fields for your hosts' =>  __('Create and customize the information fields for your hosts', 'hydra-booking'), 
            'Add more Information' =>  __('Add more Information', 'hydra-booking'), 
            'Add Information for Hosts' =>  __('Add Information for Hosts', 'hydra-booking'), 
            'Allow host to manage the dashboard.' =>  __('Allow host to manage the dashboard.', 'hydra-booking'), 
            'Allow host to create and manage meetings.' =>  __('Allow host to create and manage meetings.', 'hydra-booking'), 
            'Allow host to manage bookings and reservations.' =>  __('Allow host to manage bookings and reservations.', 'hydra-booking'), 
            'Allow host to adjust system and personal settings.' =>  __('Allow host to adjust system and personal settings.', 'hydra-booking'), 
            'Allow host to manage custom availability settings.' =>  __('Allow host to manage custom availability settings.', 'hydra-booking'), 
            'Allow host to manage integrations and external services.' =>  __('Allow host to manage integrations and external services.', 'hydra-booking'), 
            'default content' =>  __('default content', 'hydra-booking'), 
            'Field type' =>  __('Field type', 'hydra-booking'), 
            'Label' =>  __('Label', 'hydra-booking'), 
            'Enter field Label' =>  __('Enter field Label', 'hydra-booking'), 
            'Placeholder' =>  __('Placeholder', 'hydra-booking'), 
            'Options' =>  __('Options', 'hydra-booking'), 
            'Add New Option' =>  __('Add New Option', 'hydra-booking'),  
           
        );
     } 

   /* *
    * Calendar Trans String
    * 
    */ 

    public static function calendarTransString(){
       return array(
            'January' =>  _x('January', 'Calendar full month', 'hydra-booking'),   
            'February' =>  _x('February', 'Calendar full month', 'hydra-booking'),   
            'March' =>  _x('March', 'Calendar full month', 'hydra-booking'),   
            'April' =>  _x('April', 'Calendar full month', 'hydra-booking'),   
            'May' =>  _x('May', 'Calendar full month', 'hydra-booking'),
            'June' =>  _x('June', 'Calendar full month', 'hydra-booking'),   
            'July' =>  _x('July', 'Calendar full month', 'hydra-booking'),   
            'August' =>  _x('August', 'Calendar full month', 'hydra-booking'),   
            'September' =>  _x('September', 'Calendar full month', 'hydra-booking'),
            'October' =>  _x('October', 'Calendar full month', 'hydra-booking'),   
            'November' =>  _x('November', 'Calendar full month', 'hydra-booking'),   
            'December' =>  _x('December', 'Calendar full month', 'hydra-booking'),
            'Sunday' =>  _x('Sunday', 'Calendar day', 'hydra-booking'),   
            'Monday' =>  _x('Monday', 'Calendar day', 'hydra-booking'),   
            'Tuesday' =>  _x('Tuesday', 'Calendar day', 'hydra-booking'),   
            'Wednesday' =>  _x('Wednesday', 'Calendar day', 'hydra-booking'),
            'Thursday' =>  _x('Thursday', 'Calendar day', 'hydra-booking'),   
            'Friday' =>  _x('Friday', 'Calendar day', 'hydra-booking'),   
            'Saturday' =>  _x('Saturday', 'Calendar day', 'hydra-booking'), 
            'Sun' =>  _x('Sun', 'Calendar short day', 'hydra-booking'),
            'Mon' =>  _x('Mon', 'Calendar short day', 'hydra-booking'),   
            'Tue' =>  _x('Tue', 'Calendar short day', 'hydra-booking'),   
            'Wed' =>  _x('Wed', 'Calendar short day', 'hydra-booking'),
            'Thu' =>  _x('Thu', 'Calendar short day', 'hydra-booking'),
            'Fri' =>  _x('Fri', 'Calendar short day', 'hydra-booking'),   
            'Sat' =>  _x('Sat', 'Calendar short day', 'hydra-booking'),
            'Today' =>  _x('Today', 'Calendar today', 'hydra-booking'),   
            'seats left' =>  _x('seats left', 'Calendar seats left', 'hydra-booking'),   
            'Previous' =>  _x('Previous', 'Calendar previous', 'hydra-booking'),
            'Next' =>  _x('Next', 'Calendar next', 'hydra-booking'),
            'Name' =>  _x('Name', 'Calendar form name field', 'hydra-booking'),
            'Email' =>  _x('Email', 'Calendar form email field', 'hydra-booking'),
            'AM' =>  _x('AM', 'Calendar Time Format AM', 'hydra-booking'),
            'PM' =>  _x('PM', 'Calendar Time Format PM', 'hydra-booking'),
            'Bookings' =>  _x('Bookings', 'Calendar bookings', 'hydra-booking'),
            'Add New' =>  _x('Add New', 'Calendar add new', 'hydra-booking'),
            'View Details' =>  _x('View Details', 'Calendar view details', 'hydra-booking'),
            // number
            '0' => _x('0', 'Calendar number', 'hydra-booking'),
            '1' => _x('1', 'Calendar number', 'hydra-booking'),
            '2' => _x('2', 'Calendar number', 'hydra-booking'),
            '3' => _x('3', 'Calendar number', 'hydra-booking'),
            '4' => _x('4', 'Calendar number', 'hydra-booking'),
            '5' => _x('5', 'Calendar number', 'hydra-booking'),
            '6' => _x('6', 'Calendar number', 'hydra-booking'),
            '7' => _x('7', 'Calendar number', 'hydra-booking'),
            '8' => _x('8', 'Calendar number', 'hydra-booking'),
            '9' => _x('9', 'Calendar number', 'hydra-booking'),

       );
    }

    public static function tfhbTranslate($key) {
         $translations = self::calendarTransString();
         return $translations[$key] ?? $key;
   }

   public static function tfhbTranslateNumber($key) {
      return implode('', array_map(function ($letter) {
         return self::tfhbTranslate($letter);
      }, str_split((string) $key)));
   }

   public static function tfhbTranslateTimeSlot($key) {
      return self::tfhbTranslateNumber(substr($key, 0, 2)) . ':' .
            self::tfhbTranslateNumber(substr($key, 3, 2)) . ' ' .
            self::tfhbTranslate(substr($key, 6, 2));
   }
   public static function tfhbTranslateDateSlot($key) {
      // Example input: 'Tuesday, March 4'
      $dateParts = explode(', ', $key);  // Split by comma (weekday and date)
      if (count($dateParts) < 2) {
         return $key; // Return original string if format is incorrect
      }
      
      $weekday = $dateParts[0]; // 'Tuesday'
      $monthDay = $dateParts[1]; // 'March 4'
   
      // Split month and day
      $monthDayParts = explode(' ', $monthDay);
      $month = $monthDayParts[0]; // 'March'
      $day = $monthDayParts[1]; // '4'
   
      // Translate each part
      $translatedWeekday = self::tfhbTranslate($weekday);
      $translatedMonth = self::tfhbTranslate($month);
      $translatedDay = self::tfhbTranslate($day);
   
      // Return the translated string in the format 'Weekday, Month Day'
      return $translatedWeekday . ', ' . $translatedMonth . ' ' . $translatedDay;
   }

}